CREATE DATABASE SALARIES;

USE SALARIES;

CREATE TABLE USERSALARIES (
    USERID INT PRIMARY KEY,
    NAME VARCHAR(120),
    PERHOURSALARY INT DEFAULT 0,
    WORKINGHOUR INT DEFAULT 0,
    TOTALSALARY INT DEFAULT 0 
);

-- BEFORE INSERT
-- HERE MY PROGRAM CALCULATES TOTAL SALARY BEFORE IT IS INSERTED

DELIMITER //

CREATE TRIGGER BEFORE_INSERT_SALARY
BEFORE INSERT ON USERSALARIES
FOR EACH ROW
BEGIN
    SET NEW.TOTALSALARY = NEW.PERHOURSALARY * NEW.WORKINGHOUR;
END//

DELIMITER ;

INSERT INTO USERSALARIES (USERID, NAME, PERHOURSALARY, WORKINGHOUR)
VALUES (1001, 'REGVED', 900, 8);

INSERT INTO USERSALARIES (USERID, NAME, PERHOURSALARY, WORKINGHOUR)
VALUES (1002, 'AYUSH', 400, 9);

SELECT * FROM USERSALARIES;



-- AFTER INSERT
-- THIS TRIGGER ADJUSTS THE TOTALSALARY BY ADDING 100 AFTER THE RECORD IS INSERTED.


DELIMITER //

CREATE TRIGGER AFTER_INSERT_SALARY
AFTER INSERT ON USERSALARIES
FOR EACH ROW
BEGIN
    UPDATE USERSALARIES
    SET TOTALSALARY = TOTALSALARY + 100
    WHERE USERID = NEW.USERID;
END//

DELIMITER ;


INSERT INTO USERSALARIES (USERID, NAME, PERHOURSALARY, WORKINGHOUR)
VALUES (1003, 'JOHN', 800, 8);

INSERT INTO USERSALARIES (USERID, NAME, PERHOURSALARY, WORKINGHOUR)
VALUES (1009, 'DOOM', 2, 60);

INSERT INTO USERSALARIES (USERID, NAME, PERHOURSALARY, WORKINGHOUR)
VALUES (1010, 'IRON', 2, 10);

INSERT INTO USERSALARIES (USERID, NAME, PERHOURSALARY, WORKINGHOUR)
VALUES (1011, 'STARLIGHT', 1, 10);

SELECT * FROM USERSALARIES;

SHOW TRIGGERS;