USE SALARIES;


CREATE TABLE DeletedUserSalariesLog (
    USERID INT,
    NAME VARCHAR(120),
    PERHOURSALARY INT,
    WORKINGHOUR INT,
    TOTALSALARY INT,
    DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


DELIMITER //

CREATE TRIGGER BEFORE_DELETE_SALARY
BEFORE DELETE
ON USERSALARIES FOR EACH ROW
BEGIN
    INSERT INTO DeletedUserSalariesLog(USERID, NAME, PERHOURSALARY, WORKINGHOUR, TOTALSALARY, DELETED_AT)
    VALUES (OLD.USERID, OLD.NAME, OLD.PERHOURSALARY, OLD.WORKINGHOUR, OLD.TOTALSALARY, NOW());
END//

DELIMITER ;


INSERT INTO USERSALARIES(USERID, NAME, PERHOURSALARY, WORKINGHOUR)
VALUES (1012, 'SATISH', 600, 15);


SELECT * FROM USERSALARIES;

DELETE FROM USERSALARIES WHERE USERID = 1012;

SELECT * FROM DeletedUserSalariesLog;

SHOW TRIGGERS;

