SELECT * FROM APPLEMPLOYEES.dbo.INFO;

SELECT * FROM APPLEMPLOYEES.dbo.INFO
WHERE DEPTID >= 33;

UPDATE APPLEMPLOYEES.dbo.INFO SET EMPSALARY = EMPSALARY + 1000
WHERE EMPSALARY < 15000;

SELECT * FROM APPLEMPLOYEES.dbo.INFO;
