CREATE DATABASE APPLEMPLOYEES
USE APPLEMPLOYEES

CREATE TABLE INFO(
EMPID INT PRIMARY KEY NOT NULL,
EMPNAME VARCHAR(30) NOT NULL,
EMPJOB VARCHAR(30),
EMPSALARY DECIMAL(10, 2) NOT NULL,
EMPPHONE VARCHAR(20) NOT NULL,
DEPTID VARCHAR(20)
);

