USE SALARIES;

-- BEFORE UPDATE
DELIMITER //

CREATE TRIGGER BEFORE_UPDATE_SALARY
BEFORE UPDATE
ON USERSALARIES FOR EACH ROW

BEGIN

SET NEW.TOTALSALARY = NEW.PERHOURSALARY * NEW.WORKINGHOUR;

END;

DELIMITER//

-- TESTING BEFORE UPDATE
UPDATE USERSALARIES
SET WORKINGHOUR = 7 WHERE USERID = 1002;

UPDATE USERSALARIES
SET WORKINGHOUR = 10, PERHOURSALARY = 1200 WHERE USERID = 1001;

SELECT * FROM USERSALARIES;